### ISSUE TITLE
Attribute-Level Tagging for MISP Integration

### ISSUE THREAD

**Issue by semelnyk** [ninoseki/mihari#1064]
The feature I'm suggesting is the addition of attribute-level tagging functionality to Mihari rules for integration with MISP. Currently, Mihari rules support event-level tagging when pushing data to MISP, but attribute-level tagging would allow for more granular and specific categorization of data within MISP. 

<img width="394" alt="attributes" src="https://github.com/ninoseki/mihari/assets/97104452/e8e3234f-80d8-4246-8244-34020527de89">
<img width="221" alt="event" src="https://github.com/ninoseki/mihari/assets/97104452/5a7679af-4acb-48d8-89b0-53da223b1984">

<img width="359" alt="MIHARI" src="https://github.com/ninoseki/mihari/assets/97104452/ece84dd4-6333-400d-851d-fb19695e1a1c">

**Comment by ninoseki** [comment]
A straightfoward solution is adding sames tags an event has. Or do you wanto to set different tags for attributes?
(I'm not sure later one is easy to implement though)

**Comment by ninoseki** [comment]
What I mean is which one do you like:
- Set the same tags in both an event and attribute(s)
- Set different tags in an event and attribute(s)

**Comment by semelnyk** [comment]
Obviously, the 2nd option would be more preferable – having the ability to set tags separately for events and attributes would be awesome! But if that were to be an issue, even the 1st one (tags duplication) would be very helpful.
