### ISSUE TITLE
MISP not configured correctly

### ISSUE THREAD

**Issue by akes44** [ninoseki/mihari#1071]
### **Describe the bug**

Cannot get API integration with MISP server. Error is <Mihari::ConfigurationError:  Emitter:misp is not configured correctly>

### **Steps to reproduce**

- added MISP server URL to .env file (all local devices on same subnet with no firewall restrictions)
- added created new API key in MISP and added .env file
- added emitter to working rule
- saved with no error
- ran search and got AxiosError: Request failed with status code 500 in webUI. CLI logging shows Emitter:misp is not configured correctly

### **Expected behavior**

Search should be run with no errors and output of rule be created as an event in MISP

### **Actual behavior**

search failed with the above errors

### **Screenshots**

![image](https://github.com/ninoseki/mihari/assets/37227551/4aeefa02-24c2-48ef-a485-843c952ac46b)
![image](https://github.com/ninoseki/mihari/assets/37227551/28063ad9-7aba-4d13-89a0-0a4adafb567e)

**Comment by ninoseki** [comment]
There is no issue in Mihari side as far as I checked. So I guess you did something wrong.

- Put `.env` file in wrong place. You should place in the current working directory.
- Set wrong credentials. See https://ninoseki.github.io/mihari/emitters/misp/.
