### ISSUE TITLE
[Feature Request] Consider Adding Hudson Rock Cybercrime Intelligence Integration

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [ninoseki/mihari#1086]
Consider adding Hudson Rock's complimentary data to your enrichment stack to check if an email address or domain was compromised in a global Infostealer attack.

Email API sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-email?email=manvirdi2000@gmail.com
Domain API sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-domain?domain=tesla.com

Free API key and full documentation is available here: https://cavalier.hudsonrock.com/docs

Thank you.

**Comment by ninoseki** [comment]
Stop spaming.

**Comment by hudsonrock-partnerships** [comment]
That was only a suggestion. Thank you for checking this issue.
