### ISSUE TITLE
Results are not being publish to database

### ISSUE THREAD

**Issue by dhanunjayavuppala** [ninoseki/mihari#1102]
### **Describe the bug**

In somecases when i execute the rule using "mihari search rule.yml" the results or the rule entries are not being published to the databases and also to the web view, i have tried migrating the db and still same. (Attaching a debug log for your references)

### **Expected behavior**

The rule entry and the output of the rule has to be added to the database and shown in the web/api

### **Actual behavior**

In my case the results and the rule entries are not getting added to the database or web or api 

**Sample debug log**

mihari search bruteratel.yaml --debug
{
  "id": 4,
  "ruleId": "33f45b40-4bce-4f9b-8395-d69604ef2197",
  "createdAt": "2024-07-14 16:09:56 UTC",
  "artifacts": [
    {
      "id": 447,
      "data": "XXX.XXX.XXX.XXX",
      "dataType": "ip",
      "source": "shodan",
      "query": "http.html_hash:-1957161625",
      "createdAt": "2024-07-14 16:09:56 UTC",
      "tags": [
        {
          "id": 2,
          "name": "C4Framework"
        }
      ]
    }

### **System Information:**

- OS: [Sonoma 14.4.1]
- Ruby version: ruby 3.2.4
- Mihari version: 7.6.2

**Comment by ninoseki** [comment]
The data is persistent in a database (= `DATABASE_URL` / defaults to `sqlite3:mihari.db`).
Thus, I guess you are doing something wrong. For example, 
- `DATABASE_URL` in `mihari search` and `mihari web` is different
- `mihari search` and `mihari web` are executed in different hosts and they both use their own SQLite3 database (which is not accessible from each other)

**Comment by dhanunjayavuppala** [comment]
Thank you the issue has been fixed.
