### ISSUE TITLE
[Support] Ruby Selector Assistance

### ISSUE THREAD

**Issue by ssnkhan** [ninoseki/mihari#1103]
Please forgive me as I don't know Ruby well at all, and am trying to write a Feed selector to only ingest specific rows from a CSV. Specifically, given the following format CSV (containing hundreds of rows):

``` csv
82.157.154.247,Possible Cobaltstrike C2 IP
83.212.86.169,Possible Metasploit C2 IP
83.229.127.20,Possible Cobaltstrike C2 IP
```

I wish to write a selector which only selects those rows referencing Cobalt Strike. Using my extremely basic Ruby knowledge, I have tried the usual suspects, including `match` and `end_with`, however these return a boolean, rather than the full text of the row. In my IDE, I can see that `split("\n").grep(/Cobaltstrike/)` might work, but I don't think I can use grep as a selector. As my rule has an `allowed_data_types` of `ip`, I am hoping that once the entire row is returned, Mihari will automatically just ingest the IP. I have also tried to add a `.map { |v| v[0] }` such that:

``` ruby
a = "81.68.248.191,Possible Cobaltstrike C2 IP"
puts a.split("\n").grep(/Cobaltstrike/).map { |v| v[0] }
```

Leading to `selector: "split('\n').grep(/Cobaltstrike/).map { |v| v[0] }"`, however, the (IDE test) above only returns `8`, rather than the full IP. Would appreciate your advice with this!

**Comment by ninoseki** [comment]
`map { |v| v[1].include?("Cobaltstrike") ? v[0] : nil` may work.

```rb
require "csv"

require "jr/cli/core_ext"

text = '82.157.154.247,Possible Cobaltstrike C2 IP
83.212.86.169,Possible Metasploit C2 IP
83.229.127.20,Possible Cobaltstrike C2 IP'

p CSV.new(text).to_a.instance_eval { map { |v| v[1].include?("Cobaltstrike") ? v[0] : nil } }
```
