### ISSUE TITLE
[Feature Request] Alternative of IP location service

### ISSUE THREAD

**Issue by ip2location** [ninoseki/mihari#1119]
We would like to introduce an alternative of geolocation provider, [IP2Location.io](https://www.ip2location.io/). It allows 500 free geolocation queries per day without an API key. If you sign up for a free API plan and use its API key, you can get 30,000 geolocation queries. The documentation of the API can be found at https://www.ip2location.io/ip2location-documentation

Perhaps you can consider the use of the IP2Location.io API.

**Comment by ninoseki** [comment]
This project uses a free IP geolocation service operated by CIRCL (https://ip.circl.lu). 
There is zero motivation towards switching to a paid service.
