### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by ValezBGP** [ninoseki/mihari#157]
You combined really cool tools but I definitely would suggest to check spyse.com. It's similar to the mentioned tools but has some advantages

**Comment by ninoseki** [comment]
@ValezBGP How can I utilize the Spyse API?
(e.g. How can I get passive DNS records via Spyse?)

**Comment by ValezBGP** [comment]
Hey. Check out the API docs https://spyse.com/api <https://spyse.com/api>;  I think you’ll find out.

**Comment by ninoseki** [comment]
No I cannot find it on the API doc.

**Comment by ValezBGP** [comment]
Checked, weird. Seems like the changed some functonalty. I’ll ask them about that issue.

**Comment by ninoseki** [comment]
Close this issue because there is no response for a month.
