### ISSUE TITLE
Error executing (some) censys query with mihari

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mihari#201]
On Censys webpage, I did the following query **`443.https.tls.certificate.parsed.subject_dn:"CN=localhost, C=AU, ST=Some-State, O=Internet Widgits Pty Ltd" AND autonomous_system.description.raw:"DIGITALOCEAN-ASN" AND protocols:"80/http"`** and it returned 29 results but executing this same query with mihari, I got the following error:

```
*A* `Censys::ResponseError` *occured in background*: unsupported response code returned: 400
```/var/lib/gems/2.7.0/gems/censu-0.2.0/lib/censys/api.rb:261:in `block in request'
/usr/lib/ruby/2.7.0/net/http.rb:933:in `start'
/usr/lib/ruby/2.7.0/net/http.rb:606:in `start'
/var/lib/gems/2.7.0/gems/censu-0.2.0/lib/censys/api.rb:251:in `request'
/var/lib/gems/2.7.0/gems/censu-0.2.0/lib/censys/api.rb:295:in `post'
/var/lib/gems/2.7.0/gems/censu-0.2.0/lib/censys/api.rb:120:in `search'
/var/lib/gems/2.7.0/gems/censu-0.2.0/lib/censys/api.rb:31:in `search'
/var/lib/gems/2.7.0/gems/mihari-1.5.0/lib/mihari/analyzers/censys.rb:48:in `ipv4_lookup'
/var/lib/gems/2.7.0/gems/mihari-1.5.0/lib/mihari/analyzers/censys.rb:23:in `artifacts'
/var/lib/gems/2.7.0/gems/mihari-1.5.0/lib/mihari/analyzers/base.rb:57:in `normalized_artifacts'```
```
This is the following query I ran with mihari:

`mihari censys "443.https.tls.certificate.parsed.subject_dn:""CN=localhost, C=AU, ST=Some-State, O=Internet Widgits Pty Ltd"" AND autonomous_system.description.raw:""DIGITALOCEAN-ASN"" AND protocols:""80/http""" --config config.yml`

## Versions:

- `Ubuntu 20.04.2 LTS`
- `Ruby 2.7`
- `mihari 1.5.0`

**Comment by ssnkhan** [comment]
Looking at the response this appears to be query syntax error, see https://censys.io/api/v1/docs/report

> Error Responses
400 BAD REQUEST
Your query could not be executed (e.g., query could not be parsed or timed out.) See error for more information.
Example:
{"error_code":400, "error":"query could not be parsed"}

Try enclosing your query in single quotes:

```
mihari censys '443.https.tls.certificate.parsed.subject_dn:"CN=localhost, C=AU, ST=Some-State, O=Internet Widgits Pty Ltd" AND autonomous_system.description.raw:"DIGITALOCEAN-ASN" AND protocols:"80/http"' --config config.yml
```

**Comment by r0ny123** [comment]
Thanks for the suggestion, it worked!
