### ISSUE TITLE
Feature Request: IOC Refresh Interval

### ISSUE THREAD

**Issue by ssnkhan** [ninoseki/mihari#202]
Thanks again for this wonderful tool.

As I understand it, mihari will currently only import indicators if they are not already in the `mihari.db` or Postgres database. As a large amount of malicious activity is typically conducted on ephemeral instances on Digital Ocean, OVH, AWS etc, this means that an IP (for example) may never trigger another alert again, even if it has, at some point, already been ingested into the database, but is now associated with other malicious activity (i.e., originally seen hosting a Cobalt Strike Team Server, now hosting Faction C2, etc).

One idea might be to manually drop rows older than _x_ days, however my idea is that this could be configured within Mihari directly, without the need to sacrifice existing data / dropping rows. Perhaps through the creation of a new `ENV` variable called `REFRESH_INTERVAL` which would be an `INTEGER` relating to the number of days after which the same IP/IOC would be imported as new.

I have tried to check the Ruby code to see where that comparison happens, but have struggled to do so. Appreciate your consideration of this feature, and thanks for all your work on the tool thus far.

**Comment by ninoseki** [comment]
Your suggestion makes sense to me. But I'm not willing to implement the workflow you suggested because it is a little bit complicated.  I'd like to follow the KISS principle.

You can delete artifacts via SQL or the web app. Isn't it enough?
Also, the web app has APIs to automate the task.

**Comment by ssnkhan** [comment]
Appreciate your response, and I did originally think of dropping all rows based on the `created_at` field. However, there is a lot of intelligence value in retaining all detections, to see trends etc, especially for more obscure detections used by specific threat actors.

Would you be prepared to accept a PR if I sought to have this feature developed?

**Comment by ninoseki** [comment]
I just came up with an idea to implement that feature. Adding `--ignore-old-artifacts` and `--ignore-days-threshold`.
if `--ignore-old-artifacts` option is `true`, then ignore artifacts which are created `--ignore-days-threshold` days before.

```
$ mihari
...

Options:
  [--config=CONFIG]                                      # Path to the config file
  [--ignore-old-artifacts], [--no-ignore-old-artifacts]  # Whether to ignore old artifacts from checking or not.
  [--ignore-days-threshold=N]                            # Number of days to define whether is is old or not. 
                                                         # Default: 0
```

@ssnkhan What do you think?

**Comment by ssnkhan** [comment]
Wow, this is perfect! Would it be possible to also fetch the values for these from ENV variables too please?

**Comment by ninoseki** [comment]
> Would it be possible to also fetch the values for these from ENV variables too please?

Excuse me, why? I don't think that is useful.

**Comment by ssnkhan** [comment]
> > Would it be possible to also fetch the values for these from ENV variables too please?
> 
> Excuse me, why? I don't think that is useful.

I guess it would be simpler for cases where the conditions are the same for all queries. But you are right, setting `--ignore-old-artifacts` and `--no-ignore-old-artifacts` per rule is significantly more powerful.

**Comment by ninoseki** [comment]
@ssnkhan Just a question,  do these messages and options sound natural?
```bash
$ mihari
...

Options:
  [--config=CONFIG]                                      # Path to the config file
  [--ignore-old-artifacts], [--no-ignore-old-artifacts]  # Whether to ignore old artifacts from checking or not.
  [--ignore-days-threshold=N]                            # Number of days to define whether is is old or not. 
                                                         # Default: 0
```

Please let me know if you have better suggestions.

**Comment by ssnkhan** [comment]
> Just a question, do these messages and option names sound natural?

```
Options:
  [--config=CONFIG]                     # Path to the config file
  [--ignore-old-artifacts=true/false],  # Whether to ignore old artifacts from checking or not.
  [--ignore-threshold=N]                # Number of days to define whether is is old or not. 
                                        # Default: 30
```

How about a single option `--ignore-old-artifacts` with a boolean value? Default could be `false` to maintain Mihari's existing  behaviour.

Because `--ignore-days-threshold` expects an integer representing days, I think `--ignore-threshold` would be a little more concise. Hope this helps!
