### ISSUE TITLE
Feature Request: Add GreyNoise Community API Support as Analyzer

### ISSUE THREAD

**Issue by bradchiappetta** [ninoseki/mihari#206]
Hello there.  GreyNoise has recently released a Community API that we think would be a valuable addition to your tool as an additional analyzer source.  We were wondering if you would consider adding it?

https://developer.greynoise.io/reference/community-api#get_v3-community-ip

https://greynoise.io/tech

Happy to provide any additional information or classifications if needed.

**Comment by ssnkhan** [comment]
@bradchiappetta I registered for an account but it appears that the API key is time limited to two weeks. Does it automatically convert to a Community key after this time? I also can't see any documentation relating to query or rate limits for the mysterious Community API accounts.

**Comment by bradchiappetta** [comment]
@ssnkhan : Thanks so much for the quick response and for looking into our tool.

The default account is time-limited with access to all endpoints for two weeks.  Once the "trial" expires, it reverts to community access which has no expiration (the date you see on the account page, for now, is just tied to the enterprise trial.  We'll be updated this workflow in the upcoming weeks to make this easier to understand).

We haven't posted any rate limits for the Community API yet, since it is just released and we want to see what adoption is like first.  Current plans are that the Community API unauthed (so not providing an API key) will be at 50 requests per day and if you sign up for an account and use your API key, you'll get 200 requests per day.

Please let me know what other information I can provide.

**Comment by ssnkhan** [comment]
@bradchiappetta Forgive me, I'm not a Mihari developer, just a very huge fan of the tool! Thanks for clarifying details around the community API.

**Comment by bradchiappetta** [comment]
> @bradchiappetta Forgive me, I'm not a Mihari developer, just a very huge fan of the tool! Thanks for clarifying details around the community API.

@ssnkhan : No problem at all, I'm glad to spread the word about our new Community API, we're pretty excited about it.

**Comment by ninoseki** [comment]
@bradchiappetta Mihari is a tool for finding something malicious.

 It is needed to know the IP when using the community API (`https://api.greynoise.io/v3/community/{ip}`).

Thus I think it is not suitable for the tool. The GNQL API can be used along with tool but I'm not a paid user. So I have no chance to integrate it. The pay wall is a problem.

**Comment by bradchiappetta** [comment]
@ninoseki : Thanks for your thoughts on integrating the Community API.  No worries there that it isn't a good fit, I appreciate you at least looking into it.

In regards to the paid GNQL endpoint, could you explain your thoughts on how that might tie into Mihari?  If it makes sense, I'm happy to create you a VIP account for a time for the development portion, then any users that wanted to try this could take advantage of our Free 14 Day Trial and if this proves valuable, they could purchase a subscription to continue use.  Thoughts?

**Comment by ninoseki** [comment]
Excuse me, I’m not sure why I should make a sales pitch for what I didn’t ask for from myself.

**Comment by bradchiappetta** [comment]
My apologies, by no means, was I trying to make a sales pitch, if my response was received that way, I apologize.  My intent was just to offer the suggestion that users of Mihari might benefit from GreyNoise, but it seems like I was mistaken.  I will close this request, thank you for your time.
