### ISSUE TITLE
'mihari web' not found

### ISSUE THREAD

**Issue by dmoore44** [ninoseki/mihari#214]
When I try to activate the web interface with `mihari web`, I get a `Could not find command "web".` error

**Comment by ssnkhan** [comment]
I ran the `build_frontend.sh` file that was just pushed to the repo today -- but am getting a `cp: cannot stat 'dist/*': No such file or directory`.

**Comment by ninoseki** [comment]
I'm working on the `master` branch. 
It means that the latest docs do not match with the latest version of published gem. 
`mihari web` command will be included in the next release. Sorry for the inconvenience.

**Comment by ninoseki** [comment]
@dmoore44 The latest version includes `web` command.
https://rubygems.org/gems/mihari/versions/2.0.0
Please update the gem to use the command.
