### ISSUE TITLE
Feature Request: integration with CIRCL Passive SSH

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mihari#217]
CIRCL has an another service called [Passive SSH](https://github.com/D4-project/passive-ssh) which can be used for fingerprinting/tracking hosts using `specific banners`, `ssh keys` etc. With mihari we can pivot on those specifications, so it will be a nice addition for mihari.

They also operate existing Passive SSH database which can be used as a service . The api url is http://pssh.circl.lu and the endpoints can be found here https://github.com/D4-project/passive-ssh#endpoints.

**Comment by ninoseki** [comment]
@r0ny123 I don't have credentials for the service.  Thus I cannot implement the integration.

**Comment by ninoseki** [comment]
I guess that you have credentials. Then could you please work on the integration, please?
I'm willing to review your PR.

**Comment by r0ny123** [comment]
> 
> 
> @r0ny123 I don't have credentials for the service. Thus I cannot implement the integration.

Maybe @adulau can help you getting a key, I guess.

**Comment by r0ny123** [comment]
> 
> 
> I guess that you have credentials. Then could you please work on the integration, please?
> I'm willing to review your PR.

I don't think I possess enough knowledge to implement that. :/

**Comment by ninoseki** [comment]
To be clear, I don't have willingness towards coordinating the credentials to develop the integration.
I will take it into consideration if you can coordinate it for me.

**Comment by ninoseki** [comment]
Or please provide persuasive information why it is useful with practical examples.

**Comment by r0ny123** [comment]
Mihari already have support for cross searching with search engines by an SSH fingerprint, for that reason circl passive ssh can be a good search engine for this kind of stuff.


> 
> 
> To be clear, I don't have willingness towards coordinating the credentials to develop the integration.
> I will take it into consideration if you can coordinate it for me.

I asked him, but didn't get a response still, did he contact you?

**Comment by ninoseki** [comment]
No, I haven't get a contact about this.

**Comment by r0ny123** [comment]
Sorry, I didn't get any response about that. If I manage to get it done, will put up a PR.
