### ISSUE TITLE
Zoomeye cant'be queried using username & password anymore

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mihari#240]
`Zoomeye` recently changed the way how their service can be queried and introduced an API for that. So, `username` & `password` doesn't work anymore. It needs an update to reflect that.

<Ignore the bug label, it's not a really bug>

**Comment by ninoseki** [comment]
Just of of curiosity,  why did you ignore the issue template?

**Comment by ninoseki** [comment]
> <Ignore the bug label, it's not a really bug>

Really cannot understand what you mean. Please follow the template next time. Otherwise I will ignore your request.

**Comment by r0ny123** [comment]
Hey @ninoseki, I was going to fill up the issue using bug template but later thought that it was not a bug for mihari, so removed the template.
Thanks for the fix, this will not happen next time, cheers!
