### ISSUE TITLE
[BUG] Virus Total query not working

### ISSUE THREAD

**Issue by MySickSi** [ninoseki/mihari#244]
Hello,

### **Describe the bug**

When I attempt to execute the "mihari virustotal google.com", I receive an error. I have added the API key to the mihari.yml file.

I verified the API key is correct by using the same key for vt-cli.

When attempting to run the command, I receive this output.

```
ubuntu123:~/vt-cli$ mihari virustotal google.com
*A* `Mihari::Error` *occured in background*: Please configure VirusTotal API settings properly
```/var/lib/gems/2.7.0/gems/mihari-2.3.1/lib/mihari/analyzers/base.rb:80:in `rescue in set_unique_artifacts'
/var/lib/gems/2.7.0/gems/mihari-2.3.1/lib/mihari/analyzers/base.rb:76:in `set_unique_artifacts'
/var/lib/gems/2.7.0/gems/mihari-2.3.1/lib/mihari/analyzers/base.rb:43:in `run'
/var/lib/gems/2.7.0/gems/mihari-2.3.1/lib/mihari/cli.rb:106:in `run_analyzer'
/var/lib/gems/2.7.0/gems/mihari-2.3.1/lib/mihari/commands/virustotal.rb:14:in `block in virustotal'
/var/lib/gems/2.7.0/gems/mihari-2.3.1/lib/mihari/cli.rb:76:in `with_error_handling'
/var/lib/gems/2.7.0/gems/mihari-2.3.1/lib/mihari/commands/virustotal.rb:13:in `virustotal'
/var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'```
```
### **Screenshots**

Mihari call to VirusTotal with succesful vt-cli follow up;

![image](https://user-images.githubusercontent.com/40272145/117488756-c7347580-af3a-11eb-9a0f-70d42d403ffa.png)

### **System Information:**

- OS: Ubuntu 20.04 LTS
- Ruby version: 2.7.0p0
- Mihari version: Not sure where to get this

### **Additional context**

I originally had issues installing Mihari on a fresh Ubuntu 20.04 OS.

Here are the steps I took to successfully install Mihari

1. Install ruby - https://linuxize.com/post/how-to-install-ruby-on-ubuntu-20-04/#:~:text=Do%20not%20use%20sudo%20to,and%20writeable%20by%20the%20user. 

After the initial install of Ruby, Mihari would not install and I received the following error -

```
/usr/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.7.0/mkmf.rb:564:in `try_link0'
	from /usr/lib/ruby/2.7.0/mkmf.rb:582:in `try_link'
	from /usr/lib/ruby/2.7.0/mkmf.rb:801:in `try_func'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1029:in `block in have_library'
	from /usr/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1024:in `have_library'
	from extconf.rb:6:in `<main>'
```

I found the below post and followed the steps to successfully install Mihari. Is it possible Mihari is reliant on any other dependencies or an object is not in the correct path?

2. Install compiler, libraries - https://stackoverflow.com/questions/59873006/multiple-errors-while-trying-install-ruby-on-rails-through-an-ubuntu-wsl-termina 

What's also strange is the "miahri passive_dns" command works fine, and to my understanding that is reliant upon Virus Total since I have no other API configured for that command. I currently only have the Virus total and Shodan API keys configured.

**Comment by ninoseki** [comment]
> When I attempt to execute the "mihari virustotal google.com", I receive an error. I have added the API key to the mihari.yml file.

Mihari loads credentials through environmental variables by default. 
You should use `--config` option to load credentials from a YAML file.

```
Options:
  [--config=CONFIG]                                      # Path to the config file
  [--ignore-old-artifacts], [--no-ignore-old-artifacts]  # Whether to ignore old artifacts from checking or not. Only affects with analyze commands.
  [--ignore-threshold=N]                                 # Number of days to define whether an artifact is old or not. Only affects with analyze commands.
                                                         # Default: 0
```


```bash
$ mihari virustotal google.com --config mihari.yml
```
