### ISSUE TITLE
[BUG] Mihari creates MISP event with 0 attributes

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mihari#276]
### **Describe the bug**

Currently, `mihari` creates a `misp` event with 0 attributes, even if there is no new indicators in db.

### **Steps to reproduce**
Create a configuration file with `MISP_API_ENDPOINT` and `MISP_API_ENDPOINT` variable and do a simple query with that config file.

### **Expected behavior**

`mihari` should not create `misp` event with 0 attributes.

### **Screenshots**

![image](https://user-images.githubusercontent.com/49360849/122214162-65ffaa80-cec7-11eb-840f-14b3232f80ac.png)

### **System Information:**

- OS: `Ubnutu 20.04`
- Ruby version: `2.7`
- Mihari version: `Valid for all versions.`

**Comment by ninoseki** [comment]
It is an intended behavior. It indicates that there is no new finding.

**Comment by r0ny123** [comment]
I know that but is there any way to tackle this?
In the case of slack, it doesn't notify if there's no new indicator.
