### ISSUE TITLE
[Feature Request] Artifact enrichment

### ISSUE THREAD

**Issue by ninoseki** [ninoseki/mihari#310]
Implement basic enrichment for artifact to provide more contextual data in Mihari.

- Notes:
  - Provide only "basic" enrichment feature.
  - Use methods which can be used for free.

## IP address

- ASN
- Country
- ISP / organization

## Domain

- DNS:
  - A records (Optional)
  - AAAA records (Optional)
  - CNAME records (Optional)
  - TXT records (Optional)
  - NS records (Optional)
  - MX records (Optional)

- Whois:
  - Registrar (Optional)
  - Registrant (Optional)
  - Created at (Optional)
  - Updated at (Optional)
  - Expired at (Optional)

## URL

- SSL issuer (Optional)

## Data schema

Create `enrichments` table and store data in there.
An `enrichments` record has one-to-one relationship with an `artifacts` record.

**Comment by ninoseki** [comment]
@ssnkhan Let me know if you have any opnions about this topic.

**Comment by ssnkhan** [comment]
This sounds amazing! I’ve been doing this manually until now. There’s a lot of value, especially around pDNS.

**Comment by ninoseki** [comment]
Released a new version includes enrichments.
- Changelog: https://github.com/ninoseki/mihari/releases/tag/v3.6.0
