### ISSUE TITLE
[Feature Request]hashlookup.circl.lu support

### ISSUE THREAD

**Issue by adulau** [ninoseki/mihari#351]
It could be interesting to add hashlookup service from circl.lu. The API is free and documented there https://circl.lu/services/hashlookup/

Thanks a lot

**Comment by ninoseki** [comment]
@adulau Excuse me, I cannot understand your suggestion well. 
Could you explain it more specifically, please? How can I integrate the service into the tool?

**Comment by ninoseki** [comment]
I will close this issue if there is no response within a week.

**Comment by adulau** [comment]
You can do expansion of hash value (MD5, SHA-1) in mihari. If you think it's useless for your tool, then you can close this issue. Thank you.

**Comment by ninoseki** [comment]
As far as I understand, the database only contains hashes of legitimate files. Is it right?

**Comment by ninoseki** [comment]
I will close this issue because there is no response for 2 weeks.
