### ISSUE TITLE
[BUG] Shodan Query Error

### ISSUE THREAD

**Issue by ssnkhan** [ninoseki/mihari#424]
### **Describe the bug**

From this morning 04/03/2022, a number of Shodan queries are consistently returning errors that have otherwise worked for  months. I suspect this is a Shodan issue, rather than a Mihari one (possibly an update to their API, which is now returning hostnames which are not consistent with what Mihari is expecting).

### **Steps to reproduce**
Run Shodan query -- ideally where response includes hostnames consisting of FQDNs.

### **Expected behavior**
Should run without an error.

### **Actual behavior**

```
*A* `Dry::Struct::Error` *occured in background*: [Mihari::Structs::Shodan::Match.new] "set(['149.28.146.131.vultr.com', 'rebs.ga'])" (String) has invalid type for :hostnames violates constraints (type?(Array, "set(['149.28.146.131.vultr.com', 'rebs.ga'])") failed)
```/var/lib/gems/2.7.0/gems/dry-types-1.5.1/lib/dry/types/schema.rb:330:in `rescue in block in resolve_unsafe'
/var/lib/gems/2.7.0/gems/dry-types-1.5.1/lib/dry/types/schema.rb:327:in `block in resolve_unsafe'
/var/lib/gems/2.7.0/gems/dry-types-1.5.1/lib/dry/types/schema.rb:322:in `each'
/var/lib/gems/2.7.0/gems/dry-types-1.5.1/lib/dry/types/schema.rb:322:in `resolve_unsafe'
/var/lib/gems/2.7.0/gems/dry-types-1.5.1/lib/dry/types/schema.rb:62:in `call_unsafe'
/var/lib/gems/2.7.0/gems/dry-types-1.5.1/lib/dry/types/constructor.rb:87:in `call_unsafe'
/var/lib/gems/2.7.0/gems/dry-struct-1.4.0/lib/dry/struct/class_interface.rb:265:in `new'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/shodan.rb:31:in `from_dynamic!'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/shodan.rb:48:in `block in from_dynamic!'
/var/lib/gems/2.7.0/gems/mihari-3.12.0/lib/mihari/structs/shodan.rb:48:in `map'```
```

### **Screenshots**
N/A

### **System Information:**

- OS: Ubuntu
- Ruby version: 2.7
- Mihari version: [v3.12.0](https://github.com/ninoseki/mihari/releases/tag/v3.12.0) -- working on upgrading

**Comment by ninoseki** [comment]
<img width="837" alt="Screen Shot 2022-03-04 at 7 12 46 PM" src="https://user-images.githubusercontent.com/291028/156744526-ffd5a513-9d94-4a73-a660-1417953acf80.png">

https://www.shodan.io/host/149.28.146.131

I think it is a problem on Shodan side.

**Comment by ssnkhan** [comment]
Thanks Ninoseki-san, happy Friday!
