### ISSUE TITLE
[BUG] mihari web launchy error

### ISSUE THREAD

**Issue by RelaxedMind1** [ninoseki/mihari#477]
### **Describe the bug**

Running the mihari web command crashes the container with the following error.

/usr/local/bundle/gems/launchy-2.5.0/lib/launchy/applications/browser.rb:63:in `browser_cmdline': Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new (Launchy::CommandNotFoundError)

from /usr/local/bundle/gems/launchy-2.5.0/lib/launchy/applications/browser.rb:67:in `cmd_and_args'

from /usr/local/bundle/gems/launchy-2.5.0/lib/launchy/applications/browser.rb:78:in `open'

from /usr/local/bundle/gems/launchy-2.5.0/lib/launchy.rb:30:in `open'

from /usr/local/bundle/gems/mihari-4.6.0/lib/mihari/web/app.rb:55:in `block in run!'

from /usr/local/bundle/gems/puma-5.6.4/lib/rack/handler/puma.rb:70:in `run'

from /usr/local/bundle/gems/mihari-4.6.0/lib/mihari/web/app.rb:54:in `run!'

from /usr/local/bundle/gems/mihari-4.6.0/lib/mihari/commands/web.rb:22:in `web'

from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'

from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'

from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'

from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'

from /usr/local/bundle/gems/mihari-4.6.0/exe/mihari:8:in `<top (required)>'

from /usr/local/bundle/bin/mihari:25:in `load'

from /usr/local/bundle/bin/mihari:25:in `<main>'

### **Steps to reproduce**
docker run mihari web
- ...

### **Expected behavior**

Open the browser

### **Screenshots**
![image](https://user-images.githubusercontent.com/105636591/168561066-45d07bda-74ba-4c90-ac8a-fc1a387e5b66.png)

### **System Information:**

- OS: [e.g. Windows11]
- Ruby version: [e.g. 3.0.3]
- Mihari version: [e.g. 4.6.0]

**Comment by ninoseki** [comment]
Thanks for reporting.
