### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hermesthegoat** [ninoseki/mihari#480]
### **Describe the bug**

Errors when using virustotal_intelligence analyzer with an entity:url switch in the query. 'invalid type for :url' error message returned.

### **Steps to reproduce**
title: [title] # String (required)
description: [string] # String (required)

author: # (optional)
created_on: <%= Date.today %> # Date (optional)
updated_on: <%= Date.today %> # Date (optional)

tags: [] # Array<String> (Optional, defaults to [])
allowed_data_types: # Array<String> (Optional, defaults to ["hash", "ip", "domain", "url", "mail"])
  - url

disallowed_data_values:  # Array<String> (Optional, defaults to [])

ignore_old_artifacts: false # Whether to ignore old artifacts from checking or not (Optional, defaults to true)
ignore_threshold: 60 # Number of days to define whether an artifact is old or not (Optional, defaults to 0)

queries: # Array<Hash> (required)
  - analyzer: virustotal_intelligence # String (required)
    query: 'entity:url "[string]"'

### **Expected behavior**

Mihari to recognise and emit URLs - error message does contain expected URL/Value

### **Actual behavior**

2022-05-17 14:03:07.441451 E [31486:9060 error_notification.rb:14] Mihari -- Exception: Dry::Struct::Error: [Mihari::Structs::VirusTotalIntelligence::ContextAttributes.new] "[url string]" (String) has invalid type for :url violates constraints (type?(Array, "[url string]") failed)

**Comment by hermesthegoat** [comment]
Hi, please find below query used:

title: Possible C2 # String (required)

description: A collection of rules pertaining to possible teabot C2 Servers # String (required)

author: xxx # (optional)

created_on: <%= Date.today %> # Date (optional)

updated_on: <%= Date.today %> # Date (optional)

tags: [teabot, lowconfidence, c2, mobile] # Array<String> (Optional, defaults to [])

allowed_data_types: # Array<String> (Optional, defaults to ["hash", "ip", "domain", "url", "mail"])

- ip

disallowed_data_values: [url] # Array<String> (Optional, defaults to [])

ignore_old_artifacts: false # Whether to ignore old artifacts from checking or not (Optional, defaults to true)

ignore_threshold: 60 # Number of days to define whether an artifact is old or not (Optional, defaults to 0)

queries: # Array<Hash> (required)

- analyzer: virustotal_intelligence # String (required)

query: 'entity:url "/api/getbotinjects"'

- analyzer: virustotal_intelligence # String (required)

query: 'entity:url "/api/botupdate"'

Thanks

------- Original Message -------

**Comment by ninoseki** [comment]
Sorry I cannot understand anything
