### ISSUE TITLE
[Feature Request] Update Detection Behaviour

### ISSUE THREAD

**Issue by ssnkhan** [ninoseki/mihari#530]
Currently, an indicator can be configured to be ignored by Mihari if it already exists within the database, and within the timeframe set within the `ignore_threshold` attribute.

This works well, however it would be helpful if Mihari could allow the same indicator to be added, if the underlying detection rules are different. This use-case is particularly helpful when a host serves different frameworks on different ports. For example:

**Currently**: Detection Rule 1 fires, adding IP address. Detection 2 (with different detection logic) yields same host for a service running on a different port. Detection 2 not added to Mihari, as preceded by Detection 1.

**Feature Request**: Detection Rule 1 fires, adding IP address. Detection 2 (with different detection logic) yields the same host for a different service running on a different port. Detection 2 also added to the database, even though indicator is the same.

Essentially, Mihari would check both the indicator AND the Detection Rule Title (`title`), and would add the same indicator -- one row for each detection in the `artifacts` table, if the detection rules have _different_ titles. Hope this makes sense, happy to clarify further if needed.

**Comment by ninoseki** [comment]
I released v5.0.0 and it includes a change you suggested.
The new version has many breaking changes so please read the following guide. Thanks.
https://github.com/ninoseki/mihari/releases/tag/v5.0.0

**Comment by ssnkhan** [comment]
Wow, thank you so much @ninoseki 🙏🏼
