### ISSUE TITLE
[BUG] MISP emitter failing due to the 302 response code

### ISSUE THREAD

**Issue by Cehn13** [ninoseki/mihari#585]
### **Describe the bug**

After running a rule, a MISP emitter is failing due to the response code **302**.

`[18219:puma srv tp 001] Mihari -- Emission by Mihari::Emitters::MISP is failed: Unsuccessful response code returned: 302`

### **Expected behavior**

An event should be created in the MISP instance.

### **System Information:**

- OS: `Linux Mint 20.3`
- Ruby version:  `2.7. 0p0`
- Mihari version: `5.1.2`

### **Additional context**

Both the `MISP_URL` and `MISP_API_KEY` are properly configured. The auth key was tested and it lets me authenticate. When I am using a PYMISP to create an Event in the same instance, using the same auth key, the event is created. 

I am curious why Mihari's request is making MISP to respond with 302 redirection response code. Unfortunately, I can't seem to recreate the header that Mihari is sending - maybe the header is lacking something? In the https://github.com/ninoseki/mihari/blob/master/lib/mihari/clients/misp.rb headers is missing `"Accept":"application/json","Content-Type":"application/json"`, maybe that's the issue?

I can see that your code is not handling the **3##** response codes in https://github.com/ninoseki/mihari/blob/master/lib/mihari/http.rb

Why should it when the MISP documentation doesn't even account for such response codes... But maybe for any future, similar issues that could help with the redirects?

**P.S.**
It's not the issue of the `http` to `https` redirection. If I use the `http` in the MISP base URL it responds with **301** response code.

**Comment by Cehn13** [comment]
Hi @ninoseki, thank you for resolving the issue so quickly. I can confirm that the new version resolves this particular issue and MISP event is created correctly.
However, the event is added without any attributes. Should I create a separate issue for that?

**Comment by lumberjack1l** [comment]
> Hi @ninoseki, thank you for resolving the issue so quickly. I can confirm that the new version resolves this particular issue and MISP event is created correctly. However, the event is added without any attributes. Should I create a separate issue for that?

Hi, I have the same problem. After update to v5.1.3 mihari add empty event to MISP.

**Comment by ninoseki** [comment]
Thanks for sharing and I believe v5.1.4 fixes the issue.
https://github.com/ninoseki/mihari/releases/tag/v5.1.4
(I made several mistakes in #576. It's my bad)

**Comment by lumberjack1l** [comment]
> > Hi @ninoseki, thank you for resolving the issue so quickly. I can confirm that the new version resolves this particular issue and MISP event is created correctly. However, the event is added without any attributes. Should I create a separate issue for that?
> 
> Hi, I have the same problem. After update to v5.1.3 mihari add empty event to MISP.

Yeah, looks like work ;)

@ninoseki thanks!

**Comment by Cehn13** [comment]
Works for me as well :D 

Thanks @ninoseki !
