### ISSUE TITLE
[BUG] WEB APP - Page buttons on the Rules web page don't work

### ISSUE THREAD

**Issue by Cehn13** [ninoseki/mihari#589]
### **Describe the bug**

Page buttons on the Rules web page (http[:]//mihari/#/rules) don't work properly - can't be clicked.

### **Steps to reproduce**

n/a

### **Expected behavior**

Click through the pages.

### **Actual behavior**

n/a

### **Screenshots**

<img width="557" alt="image" src="https://user-images.githubusercontent.com/71849272/228241278-694f923d-3100-4e4b-83c1-f5b9b7ed1fc3.png">

### **System Information:**

- OS: `Linux Mint 20.3`
- `Ruby version: 2.7. 0p0`
- `Mihari version: 5.1.2`

### **Additional context**

n/a

**Comment by ninoseki** [comment]
The latest version v5.2.0 includes the fix for this issue.

**Comment by Cehn13** [comment]
I can confirm that the new version resolves the issue, thanks!
