### ISSUE TITLE
[Feature Request] Obfuscate or hide API keys in the Config page of the Web App

### ISSUE THREAD

**Issue by Cehn13** [ninoseki/mihari#590]
Hi @ninoseki,

Would it be possible to obfuscate API keys in the Config page of the Web App? I think that leaving the `Yes` and `No` fields with some form of obfuscated API key should be enough to determine whether we have properly configured particular service.

Obfuscated key could be in a format of first two symbols of the key and asterisks, like so: `p9*******************`

I believe it would be a more secure practice when giving access to the web app to your team internally.

**Comment by ninoseki** [comment]
How about this?
```bash
# GET /api/configs returns masked config values
$ miharii web --mask-configs

# GET /api/configs returns non-masked config values
$ mihari web 
```

**Comment by ninoseki** [comment]
The latest version v5.2.0 includes the change (#591)

**Comment by Cehn13** [comment]
Feature works great, thanks!
