### ISSUE TITLE
[Feature Request] Creating an emitter to MS Teams

### ISSUE THREAD

**Issue by Cehn13** [ninoseki/mihari#598]
Hi @ninoseki,

Would it be possible to create an Emitter to Microsoft Teams?  It uses URL webhooks - quite similar to Slack.

Here are the MS docs: https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet

And a guide on how to create a connector with python (sorry for not finding one in ruby 😄): https://towardsdatascience.com/automate-teams-with-your-first-python-alerting-bot-bcc8f7c6ee5a

Thanks!

**Comment by ninoseki** [comment]
https://cat-house-faa.notion.site/Webhook-ec6a0e3dfc644b88a34263d22f026cd3
You can implement by yourself

**Comment by Cehn13** [comment]
Got it! Sorry for not checking the Documentation in depth! I am closing the issue.

**Comment by gr00T0x** [comment]
@Cehn13 Could you please explain how you got this to work please? I am facing a similar issue at the moment.
