### ISSUE TITLE
on creating a query mihari throws errors involving undefined method for match? for the ip

### ISSUE THREAD

**Issue by prdwyer** [ninoseki/mihari#6]
ruby in centos through rvm throws the following error (IP address edited out)

Warning: undefined method `match?' for "!!!THIS IS THE RETURNED IP FROM THE API!!!":String
/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/type_checker.rb:68:in `md5?'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/type_checker.rb:18:in `hash?'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/type_checker.rb:52:in `type'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/type_checker.rb:61:in `type'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/artifact.rb:20:in `data_type'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/artifact.rb:30:in `valid?'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/analyzers/base.rb:46:in `select'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/analyzers/base.rb:46:in `normalized_artifacts'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/analyzers/base.rb:28:in `run'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/cli.rb:12:in `block in censys'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/cli.rb:52:in `with_error_handling'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/lib/mihari/cli.rb:10:in `censys'\n/usr/local/rvm/gems/ruby-2.1.10/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'\n/usr/local/rvm/gems/ruby-2.1.10/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'\n/usr/local/rvm/gems/ruby-2.1.10/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'\n/usr/local/rvm/gems/ruby-2.1.10/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'\n/usr/local/rvm/gems/ruby-2.1.10/gems/mihari-0.2.0/exe/mihari:8:in `<top (required)>'\n/usr/local/rvm/gems/ruby-2.1.10/bin/mihari:23:in `load'\n/usr/local/rvm/gems/ruby-2.1.10/bin/mihari:23:in `<main>'\n/usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `eval'\n/usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `<main>'

**Comment by ninoseki** [comment]
It seems like you are using Ruby 2.1 and mihari is only tested under Ruby 2.6.
So please update your Ruby to the latest version.
