### ISSUE TITLE
[BUG] Censys queries hanging within Docker Mihari

### ISSUE THREAD

**Issue by gr00T0x** [ninoseki/mihari#664]
### **Describe the bug**

When I run any sort of query using the censys analyzer it hangs whilst still using all of my API credits. I get no response or error until I hit the rate limit which then returns an Axios 500 error. I have tried two different sets of API keys. One for a premium account and one free account with the same issues.
### **Steps to reproduce**

Add your Censys environment variables to the Dockerfile and then create a yaml file with a Censys query. For testing I just used the Censys query from the Mihari documentation:

query: services.http.response.body_hash:"sha1:4a3ce8ee11e091dd7923f4d8c6e5b5e41ec7c047"

my env variables are set up like this in my dockerfile:

ENV CENSYS_ID=random-key-here
ENV CENSYS_SECRET=secret_goes_here

### **Actual behavior**

The Censys query runs and brings back a new alert and does not hang

### **Screenshots**

Screenshot will not really be useful as no errors are produced as such.

### **System Information:**

- OS: Ubuntu 20
- Ruby version: (ruby:3.2.2-alpine3.18)
- Mihari version: 5.2.2

### **Additional context**

N/A

**Comment by gr00T0x** [comment]
Fixed this! Docker File needs to point to the latest Mihari version! Just sent a pull request :)

**Comment by ninoseki** [comment]
Thanks and sorry for consuming your API quota. 
There is a change in Censys and #600/#610 fixed the issue. I forgot to apply the change in Dockerfile. My bad.
