### ISSUE TITLE
[BUG] Exception: TypeError: can't convert NilClass into time interval

### ISSUE THREAD

**Issue by gr00T0x** [ninoseki/mihari#666]
### **Describe the bug**

When I try to run some of my queries in CLI or web app I get the following error:
2023-08-07 10:30:48.760392 E [1:6800 error_notification.rb:12] Mihari -- Exception: TypeError: can't convert NilClass into time interval
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/shodan.rb:63:in `sleep'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/shodan.rb:63:in `block in search'
/usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/core_ext/range/each.rb:9:in `each'
/usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/core_ext/range/each.rb:9:in `each'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/shodan.rb:57:in `search'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/shodan.rb:21:in `artifacts'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/base.rb:59:in `block in normalized_artifacts'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/mixins/retriable.rb:30:in `retry_on_error'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/base.rb:58:in `normalized_artifacts'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:62:in `each'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:62:in `flat_map'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:62:in `artifacts'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:75:in `normalized_artifacts'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:91:in `unique_artifacts'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:102:in `enriched_artifacts'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:132:in `run'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/commands/search.rb:49:in `block in run'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/mixins/error_notification.rb:10:in `with_error_notification'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/commands/search.rb:48:in `run'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:75:in `normalized_artifacts'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:91:in `unique_artifacts'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:102:in `enriched_artifacts'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/analyzers/rule.rb:132:in `run'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/commands/search.rb:49:in `block in run'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/mixins/error_notification.rb:10:in `with_error_notification'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/commands/search.rb:48:in `run'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/commands/search.rb:89:in `block in search'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/database.rb:170:in `with_db_connection'
/usr/local/bundle/gems/mihari-5.3.1/lib/mihari/commands/search.rb:71:in `search'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/mihari-5.3.1/exe/mihari:8:in `<top (required)>'

### **Steps to reproduce**

Run certain rules. Interestingly the rule that is now generating the errors has been run multiple times in the past few weeks without issues.

### **Expected behavior**

I run a rule from the web app or terminal and it run fine.

### **Actual behavior**

For 2 of my rules that are no different in structure from my others fail with the above NillClass error.

### **Screenshots**

Add screenshots to help explain your problem.

### **System Information:**

OS: Ubuntu 20
Ruby version: (ruby:3.2.2-alpine3.18)
Mihari version: 5.3.1

**Comment by gr00T0x** [comment]
Forgot to add this error gets generated within seconds of running some rules

**Comment by gr00T0x** [comment]
I ran a rule with just Censys and there were no errors. I believe it is Shodan causing this. I have available API credits so unsure why this error is being caused

**Comment by gr00T0x** [comment]
I would like to caveat some rules with shodan queries still work

**Comment by ninoseki** [comment]
Thanks for the heads up and I fixed the issue in the latest version. (https://github.com/ninoseki/mihari/releases/tag/v5.3.2)
