### ISSUE TITLE
PDF in README yields 404

### ISSUE THREAD

**Issue by mavam** [ninoseki/mihari#713]
The linked presentation PDF in the README yields a 404.

**Comment by ninoseki** [comment]
Thanks for the heads up. 
The PDF is very outdated and I'm working on revamping the docs. The new docs will cover that. So let me close this PR.

**Comment by ninoseki** [comment]
FYI I completely re-written docs. 
https://ninoseki.github.io/mihari/ 
Let me know if you have any questions/comments.
