### ISSUE TITLE
[BUG] Shodan API Error - 401

### ISSUE THREAD

**Issue by gr00T0x** [ninoseki/mihari#716]
### **Describe the bug**

From about 12:00 UTC yesterday Shodan stopped working when running rules. I have tried 2 different API keys that produce the same errors.
### **Steps to reproduce**

Run a rule with a shodan query

### **Expected behavior**

Get results as expected, runs succesfully
### **Actual behavior**

The following error is received:

2023-09-29 11:47:49.482552 E [1:6800 error_notification.rb:12] Mihari -- Exception: Mihari::StatusCodeError: Unsuccessful response code returned: 401
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/http.rb:97:in `block in request'
/usr/local/lib/ruby/3.2.0/net/http.rb:1238:in `start'
/usr/local/lib/ruby/3.2.0/net/http.rb:687:in `start'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/http.rb:94:in `request'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/http.rb:30:in `get'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/http.rb:64:in `get'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/clients/base.rb:39:in `get'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/clients/shodan.rb:36:in `search'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/shodan.rb:47:in `search_with_page'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/shodan.rb:58:in `block in search'
/usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/core_ext/range/each.rb:9:in `each'
/usr/local/bundle/gems/activesupport-7.0.6/lib/active_support/core_ext/range/each.rb:9:in `each'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/shodan.rb:57:in `search'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/shodan.rb:21:in `artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/base.rb:59:in `block in normalized_artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/mixins/retriable.rb:28:in `retry_on_error'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/base.rb:58:in `normalized_artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:62:in `each'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:62:in `flat_map'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:62:in `artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:75:in `normalized_artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:91:in `unique_artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:102:in `enriched_artifacts'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/analyzers/rule.rb:132:in `run'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/commands/search.rb:49:in `block in run'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/mixins/error_notification.rb:10:in `with_error_notification'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/commands/search.rb:48:in `run'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/commands/search.rb:89:in `block in search'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/database.rb:170:in `with_db_connection'
/usr/local/bundle/gems/mihari-5.3.2/lib/mihari/commands/search.rb:71:in `search'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/mihari-5.3.2/exe/mihari:8:in `<top (required)>'
/usr/local/bundle/bin/mihari:25:in `load'
/usr/local/bundle/bin/mihari:25:in `<main>'

### **Screenshots**

Add screenshots to help explain your problem.

### **System Information:**

System Information:
OS: Ubuntu 20
Ruby version: (ruby:3.2.2-alpine3.18)
Mihari version: 5.3.2

Additional context
I am running Mihari in Docker (latest docker image used)

**Comment by ninoseki** [comment]
Do you still have this error?
I guess this is an issue of Shodan not Mihari because I'm able to use a rule with a Shodan query right now.
Mihari is a query aggregator and it can't do nothing if an API (e.g. Shodan) has an issue.

**Comment by gr00T0x** [comment]
Sorry forgot to close this. Was an issue my end apologies.
